[project]
name = "soulscape"
version = "0.2.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "black>=26.1.0",
    "isort>=7.0.0",
    "mdformat>=1.0.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.15.1",
]

[tool.uv]
package = false

[tool.uv.sources]
client = { path = "client/" }
server = { path = "server/" }
shared = { path = "shared/" }

[tool.uv.workspace]
members = ["server/", "client/", "shared/"]

[tool.black]
line-length = 80
target-version = ['py313']

[tool.isort]
profile = "black"
known_first_party = ["soulscape"]


[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "--ignore=client/ai",
]
testpaths = [
    "server/tests",
    "client/tests",
    "shared/tests",
]

